<?php
/**
 * Created by PhpStorm.
 * User: hiliq
 * Date: 2019/2/26
 * Time: 13:28
 */

namespace app\ucenter\controller;


use think\App;
use think\Controller;
use think\facade\Session;
use think\facade\View;

class BaseUcenter extends Controller
{
    protected $tpl;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->checkAuth();

    }


    public function __construct(App $app = null)
    {
        parent::__construct($app);
        if ($this->request->isMobile()){
            $this->tpl = $this->request->action();
        }else{
            $this->tpl = 'pc_'.$this->request->action();
        }

        $id = session('xwx_user_id');
        $user = \app\model\User::get($id);

        View::share([
            'url' => config('site.url'),
            'site_name' => config('site.site_name'),
            'img_site' => config('site.img_site'),
            'user' => $user
        ]);
    }

    protected function checkAuth(){
        if (!Session::has('xwx_user')) {
            $this->redirect(url('account/login'));
        }
    }
}